mod audit;
mod command;
mod config;
mod draft;
mod driver;
mod error;
mod event;
mod execution;
mod facts;
mod host;
mod ids;
mod lifecycle;
mod llm;
mod permissions;
mod plan;
mod refs;
mod resource;
mod resource_packet;
mod run;
mod snapshot;
mod tool;
pub mod tool_catalog_v4;
pub mod v2;
pub mod v2_command;
mod wire;
mod workspace;

pub const KERNEL_ABI_VERSION: &str = "deepcode.kernel.abi.v1";
pub const KERNEL_ABI_V2_VERSION: &str = "deepcode.kernel.abi.v2";
pub const KERNEL_TOOL_CATALOG_V4_VERSION: &str = "deepcode.kernel.tools.v4";

pub use command::*;
pub use config::*;
pub use draft::*;
pub use driver::*;
pub use error::*;
pub use event::*;
pub use execution::*;
pub use facts::*;
pub use host::*;
pub use ids::*;
pub use lifecycle::*;
pub use llm::*;
pub use permissions::*;
pub use plan::*;
pub use refs::*;
pub use resource::*;
pub use resource_packet::*;
pub use run::*;
pub use snapshot::*;
pub use tool::*;
pub use tool_catalog_v4::*;
pub use wire::*;
pub use workspace::*;

#[cfg(test)]
mod tests;
pub use audit::*;
